### ISSUE TITLE
Offline charging is weird! 

### ISSUE THREAD

**Issue by dr460ngeek** [gardiol/device_xiaomi_surya#2]
I power off my device and connect to charger, charging animation comes and turns off after sometimes...  But when I press power button to check the percentage of the battery, nothing shows up... I don't know what's this issue.

**Comment by gardiol** [comment]
This seems to happen only if connected to a wall charger. Connecting to PC usb device works correctly. 
Can you double check that is the case?

**Comment by dr460ngeek** [comment]
It's true that I connect it to wall charger everytime, but I tried with PC too and same problem occurs. Thank you for the reply!

**Comment by gardiol** [comment]
Can you try the latest test build from [here](https://www.gardiol.org/surya/test/lineage-18.1-20211109-UNOFFICIAL-surya-release.zip )? You will need a clean flash or flash the migrate builds zip from the telegram group...
For me this build solve the problem both on PC charge and wall charge.

**Comment by gardiol** [comment]
Can't reproduce on latest test build, closing for now.
