### ISSUE TITLE
Incoming call number bug when VoLTE is on

### ISSUE THREAD

**Issue by uaevuon** [gardiol/device_xiaomi_surya#3]
Hello.
This is bug report of incoming call number bug.

Please see the screenshot of it.
When VoLTE is on, my number is added after incoming call's number.
![135861044-15ddc9e8-0424-4a59-81fc-68aec5f70c4c](https://user-images.githubusercontent.com/3542715/140632378-0f1151fe-2cd8-4c63-bab3-085251cd867b.png)

This happens on all OSS vendor roms. This does not happen on all MIUI vendor roms.
Including this rom, all OSS roms are same.

Here is the logcat from LOS18.1 when incoming call happens.
[logcat.txt](https://github.com/gardiol/device_xiaomi_surya/files/7491729/logcat.txt)

I have no idea if this only happens on South Korea(+82) carriers. All Poco X3 custom rom users in South Korea cannot use OSS roms as daily driver because of this bug.

Hope this logcat helps fixing this bug.
Thanks.

**Comment by gardiol** [comment]
This "double" number is reported by your carrier. To fix this issue you must open a ticket upstream on LOS bug tracker, nothing that i can do here at maintainer level.
