### ISSUE TITLE
No "Screenshot" button in Recents menu

### ISSUE THREAD

**Issue by carimanola** [gardiol/device_xiaomi_surya#4]
If you open Recents menu while using an app in landscape mode the "Screenshot" button is missing. It happens if auto rotation is off in system and/or stock launcher.
If auto rotation is on in system and in stock launcher then "Screenshot" button is correctly displayed.

Auto rotation OFF:
![Screenshot_20211207-102215_Trebuchet](https://user-images.githubusercontent.com/95701824/145056896-7d5df050-78ee-42db-a548-2011ca4ed24d.png)

Auto rotation ON in system and launcher:
![Screenshot_20211208-144504_Trebuchet](https://user-images.githubusercontent.com/95701824/145274108-0da30c99-f069-4951-9742-6cbb21c9e348.png)

**Comment by gardiol** [comment]
Not a surya bug. This is LOS upstream bug, please open it there.
