### ISSUE TITLE
Duplicated privacy indicators

### ISSUE THREAD

**Issue by carimanola** [gardiol/device_xiaomi_surya#5]
Location and camera icons are duplicated in notification panel.

![Screenshot_20211208-143517_Maps](https://user-images.githubusercontent.com/95701824/145275032-8ebf651c-906f-4f08-9c20-7b3b642c3ca1.png)

![Screenshot_20211208-131502_Cámara](https://user-images.githubusercontent.com/95701824/145275048-befd3069-3199-431a-85e7-49575e3ba517.png)

**Comment by gardiol** [comment]
I see no issue here? Please reopen and explain.
